name: CI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.2', '3.3']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems

      - name: Setup
        run: |
          chmod +x ./bin/setup
          ./bin/setup

      - name: Fix missing dependencies
        run: bundle update net-pop

      - name: Install appraisals
        run: bundle exec appraisal install

      - name: Run tests
        run: bundle exec appraisal rake